M48
; DRILL file {KiCad 9.0.6+1} date 2025-12-30T10:58:30+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-30T10:58:30+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.950
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.050
%
G90
G05
T1
X255.844Y-134.656
T2
X173.375Y-87.98
X173.375Y-137.02
X241.625Y-87.98
X241.625Y-137.02
T3
X253.156Y-137.344
M30
